spring:
  datasource:
    url: jdbc:mysql://119.205.220.118:3306/teamroute?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: springuser        # ← 본인 MySQL 사용자 이름
    password: teamroute123123  # ← 실제 비밀번호 입력
    driver-class-name: com.mysql.cj.jdbc.Driver

#  jackson:
#      property-naming-strategy: SNAKE_CASE # JSON의 user_id를 Java의 userId로 변환

  jpa:
    hibernate:
      ddl-auto: none       # 이미 DB에 테이블이 있으므로 create나 update 대신 none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG # 웹 관련 로그를 자세히 출력
    # 또는 특정 Tomcat 로그를 더 자세히 보기
    org.apache.coyote.http11: DEBUG
    com.example.demo.domain.obstacle.controller: INFO

google:
  api-key: 'AIzaSyDvkKRwRsBZaJL039s7kNgoNpCjsD7gWuk'